### ISSUE TITLE
missing line of code 

### ISSUE THREAD

**Issue by tischi** [miura/NucleusRimIntensityMeasurementsV2#1]
https://github.com/miura/NucleusRimIntensityMeasurementsV2/blob/master/code/code_block2_recordNucSegV3_function.ijm#L2

and

https://github.com/miura/NucleusRimIntensityMeasurementsV2/blob/master/code/code_final.ijm#L27

I think you should add:

```
selectImage( orgId );
```

Otherwise you rely on that image being the top image before the function is called.

**Comment by miura** [comment]
done in Github, let's see if this will be pulled from Overleaf

**Comment by miura** [comment]
done. There is a GUI in overleaf to pull and merge changes in Github.
